<?php require __DIR__.'/../util.php'; require __DIR__.'/../db.php'; check_session_timeout(); ensure_csrf(); require_login_api();
$in=json_decode(file_get_contents('php://input'),true)?:[]; $id=(int)($in['id']??0); $uid=current_user_id();
if(!$id) json_response(400,['error'=>'id requerido']);
$pdo=pdo(); $stmt=$pdo->prepare("SELECT * FROM loans WHERE id=? AND user_id=?"); $stmt->execute([$id,$uid]); $l=$stmt->fetch();
if(!$l) json_response(404,['error'=>'No existe préstamo']);
if($l['status']!=='proceso') json_response(422,['error'=>'Solo se puede eliminar si está en proceso']);
$pdo->beginTransaction();
$pdo->prepare("DELETE FROM loans WHERE id=?")->execute([$id]);
$pdo->prepare("INSERT INTO loans_history (loan_id,user_id,action,meta) VALUES (?,?, 'delete', JSON_OBJECT('deleted',1))")->execute([$id,$uid]);
$pdo->commit();
audit('loans.delete',['loan_id'=>$id]); notify($uid,'Préstamo eliminado',"Se eliminó el préstamo #$id.");
json_response(200,['ok'=>true]);
